WebApplication4/Areas/AdminPanel/Controllers/ExpertController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WebApplication4.Areas.AdminPanel.Data;
using WebApplication4.DataAccessLayer;
using WebApplication4.Models;

namespace WebApplication4.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    public class ExpertController : Controller
    {
        private readonly AppDbContext _dbContext;
        private readonly IWebHostEnvironment _environment;

        public ExpertController(AppDbContext dbContext, IWebHostEnvironment environment)
        {
            _dbContext = dbContext;
            _environment = environment;
        }

        public async Task<IActionResult> Index()
        {
            var expertImages = await _dbContext.ExpertsImages.ToListAsync();
            return View(expertImages);
        }

        //public IActionResult Create() 
        //{
        //    return View();
        //}

        //public async Task<IActionResult> Create(ExpertsImage expertsImage) 
        //{
        //    if (!ModelState.IsValid)
        //        return View();

        //    if (expertsImage.Photo.IsImage()) 
        //    {
        //        ModelState.AddModelError("Photo", "File should be Image");
        //        return View();
        //    }

        //    if (expertsImage.Photo.IsAllowedSize(1))
        //    {
        //        ModelState.AddModelError("Photo", "File should not be Bigger than 1Mb");
        //        return View();
        //    }

        //    var fileName = await expertsImage.Photo.GenetareFile(Constants.ImageFolderPath);

        //    expertsImage.Name = fileName;
        //    await _dbContext.ExpertsImages.AddAsync(expertsImage);
        //    await _dbContext.SaveChangesAsync();

        //    return RedirectToAction(nameof(Index));
        //}

        public async Task<IActionResult> Update(int? id) 
        {
            if (id == null)
                return NotFound();

            var expertImage = await _dbContext.ExpertsImages.FindAsync(id);
            if (expertImage == null)
                return NotFound();

            return View(expertImage);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]

        public async Task<IActionResult> Update(int? id, ExpertsImage expertsImage) 
        {
            if (id == null)
                return NotFound();

            if(id != expertsImage.Id)
                return BadRequest();

            var existExpertImage = await _dbContext.ExpertsImages.FindAsync(id);
            if (existExpertImage == null)
                return NotFound();

            if(!ModelState.IsValid)
                return View();

            if (expertsImage.Photo.IsImage())
            {
                ModelState.AddModelError("Photo", "File should be Image");
                return View();
            }

            if (expertsImage.Photo.IsAllowedSize(1))
            {
                ModelState.AddModelError("Photo", "File should not be Bigger than 1Mb");
                return View();
            }

            var path = Path.Combine(Constants.ImageFolderPath, existExpertImage.Name);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }

            var fileName = await expertsImage.Photo.GenetareFile(Constants.ImageFolderPath);
            existExpertImage.Name = fileName;
            await _dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var expertImage = await _dbContext.ExpertsImages.FindAsync(id);
            if (expertImage == null)
                return NotFound();

            return View(expertImage);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteItem(int? id) 
        {
            if (id == null)
                return NotFound();

            var existExpertImage = await _dbContext.ExpertsImages.FindAsync(id);
            if (existExpertImage == null)
                return NotFound();

            if (!ModelState.IsValid)
                return View();

            var path = Path.Combine(Constants.ImageFolderPath, existExpertImage.Name);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }

            _dbContext.ExpertsImages.Remove(existExpertImage);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Create(ExpertsImage expertsImage)
        {
            if (!ModelState.IsValid)
                return View();
            foreach (var photo in expertsImage.Photos)
            {
            if (photo.IsImage())
            {
                ModelState.AddModelError("Photo", $"{photo.FileName} - File should be Image");
                return View();
            }

            if (photo.IsAllowedSize(1))
            {
                ModelState.AddModelError("Photo", $"{photo.FileName} - File should not be Bigger than 1Mb");
                return View();
            }

            var fileName = await photo.GenetareFile(Constants.ImageFolderPath);

                var newExpertImage = new ExpertsImage { Name = fileName };
                await _dbContext.ExpertsImages.AddAsync(newExpertImage);
                await _dbContext.SaveChangesAsync();
            }


            return RedirectToAction(nameof(Index));
        }
    }
}

WebApplication4/Areas/AdminPanel/Views/Expert/Create.cshtml
@model ExpertsImage
@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Create Expert Image</h4>
                <form class="forms-sample" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        @*<label asp-for="Photo">Photo</label>
                            <input class="form-control" placeholder="Photo" asp-for="Photo" accept="image/*">
                            <span asp-validation-for="Photo" class="text-danger"></span>*@
                        <label asp-for="Photos">Photos</label>
                        <input class="form-control" placeholder="Photos" asp-for="Photos" accept="image/*">
                        <span asp-validation-for="Photos" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <a class="btn btn-light" asp-action="Index">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationPartial" />
}

WebApplication4/Areas/AdminPanel/Views/Expert/Delete.cshtml
@model ExpertsImage
@{
    ViewData["Title"] = "Delete";
}


<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Delete Expert Image</h4>
                <img src="~/img/@Model.Image" style="width : 150px; height : 150px;" />
                <p class="text-danger mt-3"> Sure to Delete?</p>
            </div>
        </div>
    </div>
</div>
<div class="row col-12 ml-2">
    <form method="post" class="forms-sample">
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
    <a class="btn btn-light ml-1" asp-action="Index">Cancel</a>
</div>

WebApplication4/Areas/AdminPanel/Views/Expert/Index.cshtml
@model List<ExpertsImage>
@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Expert Images</h4>
                <a class="btn btn-primary" asp-action="Create">Create</a>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Image</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <img src="~/img/@item.Image "style="width: 150px; height: 150px;"/>
                                    </td>
                                    <td>
                                        <a class="btn btn-warning" asp-controller="Expert" asp-action="Update" asp-route-id="@item.Id">Update</a>
                                        <a class="btn btn-success" asp-controller="Expert" asp-action="Details" asp-route-id="@item.Id">Details</a>
                                        <a class="btn btn-danger" asp-controller="Expert" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

WebApplication4/Areas/AdminPanel/Views/Expert/Update.cshtml
@model ExpertsImage
@{
    ViewData["Title"] = "Update";
}

<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Update Expert Image</h4>
                <img src="~/img/@Model.Image" style="width : 150px; height : 150px;"/>
                <form class="forms-sample mt-2" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="Photo">Photo</label>
                        <input class="form-control" placeholder="Photo" asp-for="Photo" accept="image/*">
                        <span asp-validation-for="Photo" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <a class="btn btn-light" asp-action="Index">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>